language: node_js
node_js:
- node

services:
- docker

notifications:
  email: false

  branches:
  only:
  - master
  - development
  - Issue_156-ContinuousDelivery

matrix:
  include:
  - env: TARGET=packages/resolution
  - env: TARGET=packages/user
  - env: TARGET=packages/benefits
  - env: TARGET=packages/news

script: 
  - cd $TARGET && npm install && npm run test && chmod 400 deploy_rsa;

deploy:
  provider: script
  script: 
    - bash deploy.sh
  on:
    branch: Issue_156-ContinuousDelivery 