language: node_js
node_js:
- node

services:
- docker

notifications:
  email: false

  branches:
  only:
  - master
  - development
  - Issue_156-ContinuousDelivery

matrix:
  include:
  - env: TARGET=packages/resolution
  - env: TARGET=packages/user
  - env: TARGET=packages/benefits
  - env: TARGET=packages/news

script: 
  - cd $TARGET && npm install && npm run test && chmod 400 deploy_rsa;

before_deploy:
    - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
      -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: script
  script: 
    - bash deploy.sh
  on:
    branch: development 