language: node_js
node_js:
- node
git:
  depth: false
addons:
  ssh_known_hosts:
    - ec2-18-191-150-245.us-east-2.compute.amazonaws.com
  sonarcloud:
      organization: "epsfork"
      token: ${SONAR_TOKEN} 

services:
- docker

notifications:
  email: false

  branches:
  only:
  - master
  - development

matrix:
  include:
  - env: TARGET=packages/user
  - env: TARGET=packages/benefits
  - env: TARGET=packages/news
    before_script: 
      - npm install
      - sonar-scanner -Dsonar.projectKey=Guilherme-Aguiar_2020.1-VC_Gestor-BackEnd -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
