version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_USER: "developer"
            POSTGRES_PASSWORD: "developer"
            POSTGRES_DB: "dev_database"
        container_name: database
        volumes:
            - ./psql-scripts/init-resolution-schema.sql:/docker-entrypoint-initdb.d/init-resolution-schema.sql
            - ./psql-scripts/init-user-schema.sql:/docker-entrypoint-initdb.d/init-user-schema.sql
        ports:
            - "5432:5432"
        networks: 
            - backend 

    user:
        build: 
            context: .
            dockerfile: packages/user/Dockerfile
        container_name: user1
        volumes:
            - ./packages/user/:/usr/src/app/user
            - /usr/src/app/user/node_modules
        ports:
            - "3000:3000"
        links: 
            - postgres
        networks: 
            - backend
          
        restart: 'no'
    resolution:
        build:  
            context: .
            dockerfile: packages/resolution/Dockerfile
        container_name: resolution1
        volumes:
            - ./packages/resolution/:/usr/src/app/resolution
            - /usr/src/app/resolution/node_modules
        ports:
            - "3002:3002"
        links: 
            - postgres
        networks: 
                - backend 
        restart: 'no'
networks:
    backend:
        driver: "bridge"
